version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - app

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app/src
    environment:
      NODE_ENV: production
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app

  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: basicweatherapp
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d/
    networks:
      - app
networks:
  app: